#
# (C) Copyright IBM Corp. 2015, 2016
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#' @include ml.model.base.R
#' @include zzz.R
#' 
# This class represents a ALS model for factorization.
setClass("hydrar.als",
         representation(
           leftFactor = "SparkDataFrame",
           rightFactor = "SparkDataFrame"
         ), contains = "hydrar.model"
)

#' @title Alternating Least Squares
#' @description Performs matrix factorization using the Alternating Least Squares algorithm.
#' Two factor matrices, nameley L and R are generated by hydrar.als.
#' 
#' @param data (hydrar.matrix) a hydrar.matrix to be factorized
#' @param rank (numeric) the rank of the factorization. This value should be much smaller than 
#' the number of rows and columns of the dataset.
#' @param reg.type (character) regularization type. Supported tyeps are "L2" or "wL2". Default is "L2".
#' @param lambda (numeric) regularization parameter
#' @param iter.max (numeric) maximum number of iterations
#' @param tolerance (numeric) convergence parameter. Measures the decrease in loss between consecutive
#' iterations - if the decrease is below this threshold the algorithm will stop.
#' 
#' @return an S4 object of class /code{hydrar.als} which contains the arguments above as well as the additional fields:
#' 
#'  \tabular{rlll}{
##'   \tab\code{L}   \tab (character) \tab left factor matrix\cr
##'   \tab\code{Rt}  \tab (character) \tab right factor matrix\cr
##'   \tab\code{call}         \tab (character) \tab String representation of this method's call, including the parameters and values passed to it.\cr
#'  }  
#'  
#' @details ALS is used to calculate the best factor matrices L and R for the given input matrix. It considers different
#' user-specified regularization parameters and weights.
#' 
#' @examples \dontrun{
#' 
#'   # Create a sample dataset: 4 items, 2 users
#' df <- data.frame(X1=c(1, 0), X2=c(5, 2), "X3"=c(0, 1), "X4"=c(1, 0))
#' bm <- as.hydrar.matrix(as.hydrar.frame(df))
#' 
#' # Create a hydrar.als model
#' als <- hydrar.als(data=bm, rank=2, lambda = .1)
#' 
#' # Predict ratings for a given input list of pairs (user-id, item-id)
#' dfTest <- data.frame(userIndex=c(1, 1, 2, 2), itemIndex=c(4, 1, 2, 3))
#' bmTest <- as.hydrar.matrix(as.hydrar.frame(dfTest))
#' pred <- predict(als, bmTest)
#' 
#' }
#' 
#' @seealso \link{predict.hydrar.als}
#' @export
hydrar.als <- function(data, rank, reg.type, lambda, iter.max, tolerance) {
  new("hydrar.als", modelType="factorization", data=data,
      rank=rank, reg.type = reg.type, lambda=lambda, iter.max=iter.max, tolerance=tolerance)
}

setMethod("hydrar.model.validateTrainingParameters", signature="hydrar.als", def =
  function(model, args) {
    
    logSource <- "hydrar.als"
    
    with(args, {
      .hydrar.checkParameter(logSource, rank, inheritsFrom=c("integer", "numeric"), isOptional=T)
      .hydrar.checkParameter(logSource, reg.type, inheritsFrom=c("character"), isOptional=T)
      .hydrar.checkParameter(logSource, lambda, inheritsFrom=c("integer", "numeric"), isOptional=T)
      .hydrar.checkParameter(logSource, iter.max, inheritsFrom=c("integer", "numeric"), isOptional=T)
      .hydrar.checkParameter(logSource, tolerance, inheritsFrom=c("integer", "numeric"), isOptional=T)
    
      if (!missing(data) && missing(rank)) {
        hydrar.err(logSource, "Both data and rank arguments must be provided.")
      }    
      
      if(!missing(rank) && (rank <= 0 || rank != as.integer(rank))) {
        hydrar.err(logSource, "Parameter rank must be a positive integer number")
      }
      
      if(!missing(reg.type) && !(reg.type == "L2" || reg.type == "wL2")) {
        hydrar.err(logSource, "Parameter reg must be a either L2 or wL2")
      }
      
      if(!missing(iter.max) && (iter.max <= 0 || iter.max != as.integer(iter.max))) {
        hydrar.err(logSource, "Parameter iter.max must be a positive integer")
      }
      
      if(!missing(lambda) && (lambda < 0)) {
        hydrar.err(logSource, "Parameter lambda must be a non negative real number")
      }
      
      if(!missing(tolerance) && (tolerance < 0)) {
        hydrar.err(logSource, "Parameter tolerance must be a non negative real number")
      }
                
      #check if rank is smaller than the dimensions of the data matrix
      if(!missing(data) && (nrow(data) < rank || ncol(data) < rank)){
        hydrar.err(logSource, "Parameter rank must be smaller than the number of rows and columns of the input matrix")
      }
                
    })
    return(model)
  }
)


setMethod("hydrar.model.buildTrainingArgs", signature="hydrar.als", def =
  function(model, args) {
    with(args, {
      
      directory <- hydrar.env$WORKSPACE_ROOT("hydrar.ml.model.als")
      
      # configuration and data paths - DML returns errors without the pathing arguments
      leftFactorPath <- directory %++% "/L";
      rightFactorPath <- directory %++% "/R";
      VcopyPath <- directory %++% "/V"; 
      

      dmlPath <- file.path(hydrar.env$SYSML_ALGO_ROOT(), hydrar.env$DML_ALS_DS_SCRIPT)
      dmlArgs <- list(dml = dmlPath, V=data, "L", "Rt", check=TRUE, fmt='CSV')
      
      # if (conjugate_gradient) {
      #   dmlArgs <- list(dml = dmlPath, V=data, "L", "Rt", ibL=leftFactorPath, R=rightFactorPath, M=VcopyPath, check=TRUE, fmt='CSV')
      # }
      
      if (!missing(lambda)) {
        dmlArgs <- c(dmlArgs, lambda=lambda)
      }
      if (!missing(reg.type)) {
        dmlArgs <- c(dmlArgs, reg=reg.type)
      }
      if (!missing(rank)) {
        dmlArgs <- c(dmlArgs, rank=rank)
      }
      if (!missing(iter.max)) {
        dmlArgs <- c(dmlArgs, maxi=iter.max)
      }
      if (!missing(tolerance)) {
        dmlArgs <- c(dmlArgs, thr=tolerance)
      }
      model@dmlArgs <- dmlArgs
      return(model)
    })
  }
)

setMethod("hydrar.model.postTraining", signature = "hydrar.als", def =
  function (model) {
    model@leftFactor <- model@dmlOuts$sysml.execute$L
    model@rightFactor <- model@dmlOuts$sysml.execute$Rt
    return(model)
  }
)


#' Predict method for Alternating Least Squares
#' @name predict.hydrar.als
#' @description The \code{predict.hydrar.als} function predicts ratings using previously generated factor
#' matrices: L and R.
#' @param data (hydrar.matrix) The input data can be a list of user-ids. In this case top recommendations will be
#' predicted. It can also be a list of (user-id, item-id) pairs. In this case the prediction will be made for each 
#' pair individually. 
#' @param type (character) Equal to "pairs" or "topk"
#' @param k (numeric) The number of top k items. This paramet is applicable only if predictTop=TRUE
#' @param object (hydrar.als) The ALS Model
#' 
#' @return The result is a \code{hydrar.matrix} which contain a list of triples: {user-id, item-id, rating} if
#' predictTop=FALSE or a list of top recommendations for each user if predictTop=TRUE
#' 
#' @details Factorization based prediction can be used to make recommendations or in general for predictions based on 
#' factor matrices L and R.
#' 
#' @examples \dontrun{
#' 
#'   # Create a sample dataset: 4 items, 2 users
#' df <- data.frame(X1=c(1, 0), X2=c(5, 2), "X3"=c(0, 1), "X4"=c(1, 0))
#' bm <- as.hydrar.matrix(as.hydrar.frame(df))
#' 
#' # Create a hydrar.als model
#' als <- hydrar.als(data=bm, rank=2, lambda = .1)
#' 
#' # Predict ratings for a given input list of pairs (user-id, item-id)
#' dfTest <- data.frame(userIndex=c(1, 1, 2, 2), itemIndex=c(4, 1, 2, 3))
#' bmTest <- as.hydrar.matrix(as.hydrar.frame(dfTest))
#' pred <- predict(als, bmTest)
#' #TODO In future, implement summary / show function
#' SparkR::collect(pred)
#' 
#' }
#' 
#' @seealso \link{hydrar.als}
#' 
predict.hydrar.als <- function(object, data, type, k){
  
  logSource <- "predict.hydrar.als"
  
  type <- ifelse(missing(type), hydrar.env$ALS_PAIR, type);
  modelDir <- object@modelPath;
  directory <- hydrar.env$WORKSPACE_ROOT("hydrar.ml.model.als")
  
  
  .hydrar.checkParameter(logSource, data, inheritsFrom="hydrar.matrix", isOptional=F);
  .hydrar.checkParameter(logSource, directory, inheritsFrom="character", checkExistence=T, expectedExistence=F);
  .hydrar.checkParameter(logSource, type, inheritsFrom="character", isOptional=T);
  .hydrar.checkParameter(logSource, k, inheritsFrom=c("integer","numeric"), isOptional=T);
  
  if (!(type %in% c(hydrar.env$ALS_PAIR, hydrar.env$ALS_TOPK))){
    hydrar.err(logSource, "Type must have values pair or topk ");
  }
  
  
  k <- ifelse(missing(k), 5, k);
  
  #check that data has 2 columns
  if (type == hydrar.env$ALS_PAIR & ncol(data) != 2){
    hydrar.err(logSource, "Test data has to have 2 columns: (user-id, item-id) pairs");
  }else if(type == hydrar.env$ALS_TOPK & ncol(data) != 1){
    hydrar.err(logSource, "Test data for top predictions has to have 1 column: the list of user ids");
  }

  #verify that all pairs of user-id and password exist in factor matrices
  #TODO In future, don't store the entire input data - just store the number of rows an columns.
  V <- object@dmlArgs$V
  n <- nrow(V);
  m <- ncol(V);
  vp_colnames <- columns(V)
  
  dmlScript <- file.path(hydrar.env$SYSML_ALGO_ROOT(), hydrar.env$DML_ALS_PREDICT_SCRIPT);
  
  # TODO: Enable when we add topK script
  # if (type == hydrar.env$ALS_TOPK){
  #   dmlScript <- file.path(hydrar.env$SYSML_ALGO_ROOT(), hydrar.env$DML_ALS_TOP_PREDICT_SCRIPT)
  #   data_colnames <- c("user")
  # }

  args = list(X = data, dml=dmlScript, L=object@dmlOuts$sysml.execute$L, 
              R=object@dmlOuts$sysml.execute$Rt, Y=directory %++% "/prediction" %++% hydrar.env$FBP_SUFFIX,
              "V_prime");
  
  if (type == hydrar.env$ALS_PAIR){
    args <- c(args, Vrows=n);
    args <- c(args, Vcols=m);
    args <- c(args, fmt = "TEXT");
  }else{
    args <- c(args, V=V@dataPath);
    args <- c(args, K=k);
    args <- c(args, fmt = "CSV");
  }
  
  # execute factorization based predict dml script
  dmlErr <- do.call("sysml.execute", args);
  
  # access the output
  Vp <- dmlErr$V_prime
  SparkR::colnames(Vp) <- vp_colnames
  
  return(Vp)
}
